---
- name: Run Shell Script
  hosts: all
  become: true
  gather_facts: false
  vars:
    shell_script: undef

  pre_tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: false
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: "Install packages"
      ansible.builtin.apt: "name={{ item }} state=present"
      with_items:
        - postgresql
        - curl
        - acl

  tasks:
    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: "Start and enable PostgreSQL service"
      service: "name=postgresql state=started enabled=yes"

    - name: Fetch init file
      ansible.builtin.shell: "curl -O https://raw.githubusercontent.com/Eduardo-Cerqueira/demeter/staging/init.sql"

    - name: Initialize PostgreSQL
      become: true
      become_user: postgres
      command: psql -c '\i ./init.sql'
